### ISSUE TITLE
Emojis not working on windows 8.1

### ISSUE THREAD

**Issue by iamfredrickokereke** [idleberg/sublime-emoji-code#1]
Am a beginner and tried to follow the guide, I have successfully installed the package control but no action from the emoji code. kindly check and revert if this is a bug or help with a more friendly guide to confirm it works. Apologies if am in no place to make these demands.

![image](https://user-images.githubusercontent.com/38326256/50737327-13831580-11c8-11e9-84bd-8506783adba9.png)

**Comment by idleberg** [comment]
The screenshot shows a dialog from the [Emoji](https://packagecontrol.io/packages/Emoji) package, not my _Emoji Code_ package.
